/**
 * @internal
 * The template of all YCloud icon components.
 */
export const ycloudIconTemplate = `@if (title(); as titleValue) {
  <title>{{ titleValue }}</title>
}
<ng-content select="title"></ng-content>
@for (child of iconNodes(); track child[1]['key'] ?? $index) {
  @let attrs = child[1];
  @switch (child[0]) {
    @case ('path') {
      <svg:path
        [attr.d]="attrs['d']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
    @case ('line') {
      <svg:line
        [attr.x1]="attrs['x1']"
        [attr.x2]="attrs['x2']"
        [attr.y1]="attrs['y1']"
        [attr.y2]="attrs['y2']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
    @case ('polygon') {
      <svg:polygon
        [attr.points]="attrs['points']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
    @case ('polyline') {
      <svg:polyline
        [attr.points]="attrs['points']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
    @case ('circle') {
      <svg:circle
        [attr.cx]="attrs['cx']"
        [attr.cy]="attrs['cy']"
        [attr.r]="attrs['r']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
    @case ('ellipse') {
      <svg:ellipse
        [attr.cx]="attrs['cx']"
        [attr.cy]="attrs['cy']"
        [attr.rx]="attrs['rx']"
        [attr.ry]="attrs['ry']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
    @case ('rect') {
      <svg:rect
        [attr.x]="attrs['x']"
        [attr.y]="attrs['y']"
        [attr.width]="attrs['width']"
        [attr.height]="attrs['height']"
        [attr.rx]="attrs['rx']"
        [attr.ry]="attrs['ry']"
        [attr.fill]="attrs['fill']"
        [attr.stroke]="attrs['stroke']"
        [attr.stroke-width]="attrs['stroke-width']"
        [attr.stroke-linecap]="attrs['stroke-linecap']"
        [attr.stroke-linejoin]="attrs['stroke-linejoin']"
        [attr.stroke-miterlimit]="attrs['stroke-miterlimit']"
        [attr.fill-rule]="attrs['fill-rule']"
        [attr.clip-rule]="attrs['clip-rule']"
        [attr.opacity]="attrs['opacity']"
        [attr.fill-opacity]="attrs['fill-opacity']"
        [attr.stroke-opacity]="attrs['stroke-opacity']"
        [attr.transform]="attrs['transform']"
        [attr.pathLength]="attrs['pathLength']"
        [attr.vector-effect]="attrs['vector-effect']"
        [attr.class]="attrs['class']"
        [attr.id]="attrs['id']"
      />
    }
  }
}
<ng-content />`;
